### ISSUE TITLE
image could not be loaded

### ISSUE THREAD

**Issue by Sullivan6fu** [Tpool1/dcm_npy_loader#1]
it keeps saying image XXXX.JPEG could not be loaded,i dont know what went wrong...

Maybe the format of my image dataset does not match yours？

**Comment by Tpool1** [comment]
Hello! All images have to be in Dicom format. If you are working with medical imagery and you convert them to jpeg first, it applies a compression algorithm and somewhat distorts them. Sorry, I did not see this comment until now.

**Comment by Tpool1** [comment]
README has been updated to make this more clear.
